# Generated by Django 5.1.4 on 2025-01-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('average_score', models.FloatField()),
                ('parent_income', models.FloatField()),
                ('dependents', models.IntegerField()),
                ('decent_house', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('is_benefit', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CalonPenerima',
        ),
        migrations.DeleteModel(
            name='Kriteria',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
