# Generated by Django 5.1.4 on 2025-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_applicant_criteria_delete_calonpenerima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField()),
                ('apakah_keuntungan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kata_sandi', models.CharField(max_length=255)),
                ('nilai_rata_rata', models.FloatField()),
                ('penghasilan_orangtua', models.FloatField()),
                ('tanggungan', models.IntegerField()),
                ('rumah_layak', models.BooleanField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
