# Generated by Django 5.1.4 on 2025-01-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_kriteria_pendaftar_delete_applicant_delete_criteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kriteria',
            old_name='apakah_keuntungan',
            new_name='is_benefit',
        ),
    ]
