# Generated by Django 5.1.4 on 2025-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_applicant_criteria_delete_kriteria_delete_pendaftar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='decent_house',
            field=models.IntegerField(choices=[(1, 'Sangat Layak'), (2, 'Layak'), (3, 'Cukup'), (4, 'Kurang Layak'), (5, 'Tidak Layak')]),
        ),
    ]
