# Generated by Django 5.1.4 on 2025-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_applicant_user_alter_applicant_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
