# Generated by Django 5.1.4 on 2025-01-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0009_user_otp_code_user_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
    ]
